# Generated by Django 6.0.7 on 2026-09-25 13:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='The code customers enter, e.g. SUMMER20', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage (%)'), ('fixed', 'Fixed Amount (PKR)')], default='percentage', max_length=15)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (0-100) or fixed PKR amount.', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('minimum_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Total number of times this coupon can be used. NULL = unlimited.', null=True)),
                ('usage_limit_per_user', models.PositiveIntegerField(default=1, help_text='How many times a single user can use this coupon.')),
                ('times_used', models.PositiveIntegerField(default=0, help_text='Auto-incremented. Do not edit manually.')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'indexes': [models.Index(fields=['code'], name='coupons_cou_code_3bf721_idx'), models.Index(fields=['is_active', 'valid_from', 'valid_to'], name='coupons_cou_is_acti_9cc365_idx')],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=50)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='coupons.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coupon Usage',
                'verbose_name_plural': 'Coupon Usages',
                'unique_together': {('coupon', 'user', 'order_number')},
            },
        ),
    ]
