# Generated by Django 6.0.7 on 2026-09-25 13:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='1 (worst) to 5 (best).', validators=[django.core.validators.MinValueValidator(1, message='Minimum rating is 1 star.'), django.core.validators.MaxValueValidator(5, message='Maximum rating is 5 stars.')])),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('is_verified_purchase', models.BooleanField(default=False, help_text='Set to True if the user has a delivered order containing this product.')),
                ('status', models.CharField(choices=[('pending', 'Pending Moderation'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('helpful_count', models.PositiveIntegerField(default=0, help_text='How many users marked this review as helpful.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'status'], name='reviews_rev_product_0aaa55_idx'), models.Index(fields=['user'], name='reviews_rev_user_id_a65d48_idx')],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
